services:
  reflexio:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./reflexio/data:/reflexio/data
      - ./reflexio/server/site_var/site_var_sources:/reflexio/server/site_var/site_var_sources
    environment:
      - LOCAL_STORAGE_PATH=/reflexio/data
      - SQLITE_FILE_DIRECTORY=/reflexio/data
      - OPENAI_API_KEY=sk-proj-
    restart: unless-stopped

# volumes:
#   reflexio-data:
#   reflexio-site-vars:
